name: Test Coverage

on: [push, pull_request]

permissions:
  contents: read

env:
  COVERAGE: PartialSummary

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true

    - name: Run tests
      run: bundle exec bake test

    - name: Validate coverage
      run: bundle exec bake covered:validate --paths .covered.db \;
